export const bloodGroups = ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"];
export const city = [
  "Abramacity",
  "Adalajcity",
  "Ahmedabadcity",
  "Ahwacity",
  "Amodcity",
  "Amrelicity",
  "Amrolicity",
  "Anandcity",
  "Anjarcity",
  "Ankleshwarcity",
  "Babracity",
  "Bagasaracity",
  "Bagasracity",
  "Banas Kanthacity",
  "Bantvacity",
  "Bardolicity",
  "Bedicity",
  "Bhachaucity",
  "Bhanvadcity",
  "Bharuchcity",
  "Bhavnagarcity",
  "Bhayavadarcity",
  "Bhujcity",
  "Bilimoracity",
  "Bilkhacity",
  "Borsadcity",
  "Botadcity",
  "Chaklasicity",
  "Chalalacity",
  "Chanasmacity",
  "Chhalacity",
  "Chhota Udepurcity",
  "Chikhlicity",
  "Chotilacity",
  "Dabhoicity",
  "Dahegamcity",
  "Dahodcity",
  "Dakorcity",
  "Damnagarcity",
  "Dangs (India)city",
  "Dayaparcity",
  "Delvadacity",
  "Delwadacity",
  "Devbhumi Dwarkacity",
  "vgadh Bariyacity",
  "Dhandhukacity",
  "Dhaneracity",
  "Dharampurcity",
  "Dharicity",
  "Dholacity",
  "Dholkacity",
  "Dhorajicity",
  "Dhrangadhracity",
  "Dhrolcity",
  "Dhuwarancity",
  "Disacity",
  "Dohadcity",
  "Dungarpurcity",
  "Dwarkacity",
  "Gadhadacity",
  "Gandevicity",
  "Gandhidhamcity",
  "Gandhinagarcity",
  "Gariadharcity",
  "Ghoghacity",
  "Gir Somnathcity",
  "Godhracity",
  "Gondalcity",
  "Halolcity",
  "Halvadcity",
  "Hansotcity",
  "Harijcity",
  "Himatnagarcity",
  "Jalalporecity",
  "Jalalpurcity",
  "Jambusarcity",
  "Jamnagarcity",
  "Jasdancity",
  "Jetalsarcity",
  "Jetpurcity",
  "Jhulasancity",
  "Jodhpurcity",
  "Jodiacity",
  "Jodiya Bandarcity",
  "Junagadhcity",
  "Kachchhcity",
  "Kadicity",
  "Kadodcity",
  "Kalavadcity",
  "Kalolcity",
  "Kandlacity",
  "Kanodarcity",
  "Kapadvanjcity",
  "Karamsadcity",
  "Kathorcity",
  "Katpurcity",
  "Kavantcity",
  "Kawantcity",
  "Keshodcity",
  "Khambhaliacity",
  "Khambhatcity",
  "Khedacity",
  "Khedbrahmacity",
  "Kheralucity",
  "Kodinarcity",
  "Kosambacity",
  "Kundlacity",
  "Kutch districtcity",
  "Kutiyanacity",
  "Lakhtarcity",
  "Lalpurcity",
  "Lathicity",
  "Limbdicity",
  "Lunavadacity",
  "Mahemdavadcity",
  "Mahesanacity",
  "Mahudhacity",
  "Malpurcity",
  "Manavadarcity",
  "Mandalcity",
  "Mandvicity",
  "Mandvi (Surat)city",
  "Mangrolcity",
  "Mansacity",
  "Meghrajcity",
  "Mehsanacity",
  "Mendardacity",
  "Modasacity",
  "Morbicity",
  "Morva (Hadaf)city",
  "Morwacity",
  "Mundracity",
  "Nadiadcity",
  "Naliyacity",
  "Narmadacity",
  "Narodacity",
  "Navsaricity",
  "Okhacity",
  "Olpadcity",
  "Paddharicity",
  "Padracity",
  "Palanpurcity",
  "Palitanacity",
  "Paliyadcity",
  "Panch Mahalscity",
  "Panchmahal districtcity",
  "Pardicity",
  "Parneracity",
  "Patancity",
  "Pavi Jetpurcity",
  "Petladcity",
  "Porbandarcity",
  "Radhanpurcity",
  "Rajkotcity",
  "Rajpiplacity",
  "Rajulacity",
  "Ranavavcity",
  "Raparcity",
  "Rohacity",
  "Sabar Kanthacity",
  "Sachincity",
  "Salayacity",
  "Sanandcity",
  "Sankhedacity",
  "Sarkhejcity",
  "Savarkundlacity",
  "Saylacity",
  "Shahpurcity",
  "Shivrajpurcity",
  "Siddhpurcity",
  "Sihorcity",
  "Sikkacity",
  "Sinorcity",
  "Sojitracity",
  "Songadhcity",
  "Suratcity",
  "Surendranagarcity",
  "Talajacity",
  "Tankaracity",
  "Tapicity",
  "Thancity",
  "Thangadhcity",
  "Tharadcity",
  "Thasracity",
  "The Dangscity",
  "Umralacity",
  "Umrethcity",
  "Uncity",
  "Unacity",
  "Unjhacity",
  "Upletacity",
  "Utrancity",
  "Vadnagarcity",
  "Vadodaracity",
  "Vaghodiacity",
  "Vallabh Vidyanagarcity",
  "Vallabhipurcity",
  "Valsadcity",
  "Vansdacity",
  "Vapicity",
  "Vartejcity",
  "Vasacity",
  "Vasocity",
  "Vejalpurcity",
  "Veravalcity",
  "Vijapurcity",
  "Vinchhiyacity",
  "Vinchiacity",
  "Virpurcity",
  "Visavadarcity",
  "Visnagarcity",
  "Vyaracity",
  "Wadhaicity",
  "Wadhwancity",
  "Waghaicity",
  "Wankanercity",
]
export const state = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
]
export const countries = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, Democratic Republic of the Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D'Ivoire",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and Mcdonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, the Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Serbia and Montenegro",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.s.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
]
export const formFields = [
  {
    id: "firstname",
    label: "First Name",
    placeholder: "Hardi",
    type: "text",
  },
  {
    id: "middlename",
    label: "Middle Name",
    placeholder: "Ketankumar",
    type: "text",
  },
  {
    id: "lastname",
    label: "Last Name",
    placeholder: "Mehta",
    type: "text",
  },
  {
    id: "mobilenumber",
    label: "Mobile Number",
    placeholder: "9999000112",
    type: "text",
  },
  {
    id: "email",
    label: "Email",
    placeholder: "upforce@gmail.com",
    type: "email",
  },
  {
    id: "birthdate",
    label: "Birthday",
    type: "date",
  },
  {
    id: "age",
    label: "Age",
    placeholder: "23",
    type: "number",
  },
  {
    id: "bloodgroup",
    label:"Blood Groups",
    options: bloodGroups,
    type: "select",
  },
  {
    id: "height",
    label: "Height",
    placeholder: "5.0",
    type: "number",
  },
  {
    id: "weight",
    label: "Weight",
    placeholder: "40",
    type: "number",
  },
  {
    id: "gender",
    label: "Gender",
    options: ["Female", "Male"],
    type: "radio",
  },
  {
    id: "maritalstatus",
    label: "Marital Status",
    options: ["Single", "Married", "Divorced", "Widowed"],
    type: "radio",
  },
];

export const addressFormFields = [
  {
    id: "addLine1",
    label: "Address Line 1",
    placeholder: "Pakwan Chock",
    type: "text",
  },
  {
    id: "addLine2",
    label: "Address Line 2",
    placeholder: "Bodakdev, Ahmedabad",
    type: "text",
  },
  {
    id: "city",
    label:"City",
    options: city,
    type: "select",
  },
  {
    id: "state",
    label:"State",
    options: state,
    type: "select",
  },
  {
    id: "country",
    label:"Countries",
    options: countries,
    type: "select",
  },
  {
    id: "pincode",
    label: "PinCode",
    type: "number",
  },
  
];
